import { AdminLanguage } from './types';

export const TRANSLATIONS: { [lang in AdminLanguage]: { [key: string]: string } } = {
  en: {
    adminPanelTitle: 'Admin Panel',
    gameSettings: 'Game Settings',
    numDice: 'Number of Dice:',
    oneDie: 'One',
    twoDice: 'Two',
    questionBank: 'Question Bank',
    addQuestion: 'Add New Question',
    questionLabel: 'Question:',
    answerLabel: 'Answer:',
    pointsLabel: 'Points:',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    noQuestions: 'No questions yet. Add some to start the game!',
    dangerZone: 'Danger Zone',
    language: 'Language:',
    close: 'Close',
    studentRoster: 'Student Roster',
    activeStudent: 'Active Student',
    noStudents: 'Add students in the admin panel to begin.',
    addStudent: 'Add Student',
    studentName: 'Student Name:',
    manageStudents: 'Manage Students',
    resetAllScores: 'Reset All Scores',
    resetAllScoresConfirmation: 'Are you sure you want to reset all scores to 0?',
    submitAnswer: 'Submit',
    correct: 'Correct!',
    incorrect: 'Incorrect. The correct answer is:',
    rollDiceSingular: 'Roll Die',
    rollDicePlural: 'Roll Dice',
    selectStudent: 'Select a student to start playing.',
    yourAnswer: 'Your Answer...',
    importQuestions: 'Import Questions',
    exportQuestions: 'Export Questions',
    importStudents: 'Import Students',
    exportStudents: 'Export Students',
    sortByName: 'Sort by Name',
    sortByScore: 'Sort by Score',
    deleteQuestionConfirmation: 'Are you sure you want to delete this question?',
    deleteStudentConfirmation: 'Are you sure you want to delete this student?',
    // New translations for intra-file conflict modal
    intraFileConflictTitle: 'Duplicate IDs in Import File',
    intraFileConflictDescription: 'The imported file contains multiple items with the same ID. Please edit the IDs below to make them unique before continuing.',
    conflictingId: 'Conflicting ID',
    conflictingItems: 'Conflicting Items',
    resolveAndContinue: 'Resolve and Continue Import',
    cancelImport: 'Cancel Import',
  },
  he: {
    adminPanelTitle: 'פאנל ניהול',
    gameSettings: 'הגדרות משחק',
    numDice: 'מספר קוביות:',
    oneDie: 'אחת',
    twoDice: 'שתיים',
    questionBank: 'מאגר שאלות',
    addQuestion: 'הוסף שאלה חדשה',
    questionLabel: 'שאלה',
    answerLabel: 'תשובה:',
    pointsLabel: 'נקודות:',
    save: 'שמור',
    cancel: 'בטל',
    edit: 'ערוך',
    delete: 'מחק',
    noQuestions: 'אין עדיין שאלות. הוסף כמה כדי להתחיל את המשחק!',
    dangerZone: 'אזור סכנה',
    language: 'שפה:',
    close: 'סגור',
    studentRoster: 'רשימת תלמידים',
    activeStudent: 'תלמיד/ה בתור',
    noStudents: 'יש להוסיף תלמידים בפאנל הניהול.',
    addStudent: 'הוסף תלמיד/ה',
    studentName: 'שם התלמיד/ה',
    manageStudents: 'ניהול תלמידים',
    resetAllScores: 'איפוס כל הנקודות',
    resetAllScoresConfirmation: 'האם אתה בטוח שברצונך לאפס את כל הנקודות ל-0?',
    submitAnswer: 'הגש תשובה',
    correct: 'נכון!',
    incorrect: 'לא נכון. התשובה הנכונה היא:',
    rollDiceSingular: 'גלגל את הקוביה',
    rollDicePlural: 'גלגל את הקוביות',
    selectStudent: 'יש לבחור תלמיד/ה כדי להתחיל.',
    yourAnswer: 'התשובה שלך...',
    importQuestions: 'ייבוא שאלות',
    exportQuestions: 'ייצוא שאלות',
    importStudents: 'ייבוא תלמידים',
    exportStudents: 'ייצוא תלמידים',
    sortByName: 'מיון לפי שם',
    sortByScore: 'מיון לפי ניקוד',
    deleteQuestionConfirmation: 'האם אתה בטוח שברצונך למחוק שאלה זו?',
    deleteStudentConfirmation: 'האם אתה בטוח שברצונך למחוק תלמיד/ה זה?',
    // New translations for intra-file conflict modal
    intraFileConflictTitle: 'מזהים כפולים בקובץ הייבוא',
    intraFileConflictDescription: 'הקובץ המיובא מכיל מספר פריטים עם אותו מזהה. אנא ערוך את המזהים למטה כדי להפוך אותם לייחודיים לפני שתמשיך.',
    conflictingId: 'מזהה כפול',
    conflictingItems: 'פריטים מתנגשים',
    resolveAndContinue: 'פתור והמשך בייבוא',
    cancelImport: 'בטל ייבוא',
  },
};